secretGenerator:
  - name: mysql-pass
    literals:
      - password=your-password-here
resources:
  - wordpress/mysql-service.yaml
  - wordpress/mysql-pvc.yaml
  - wordpress/mysql-deployment-v2.yaml
  - wordpress/wordpress-deployment.yaml
